import { test, expect } from "@playwright/test";
import { expectNoHorizontalOverflow, failOnConsoleErrors } from "./_helpers";

test("renders a diagram generated by the real package", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator(".erd > svg")).toBeVisible();
});

test("the diagram contains the schema's tables", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator(".erd")).toContainText("Comment");
  await expect(page.locator(".erd")).toContainText("Post");
});

test("primary and foreign keys are marked", async ({ page }) => {
  await page.goto("/");
  // Regression cover: mongoose reports "ObjectId", and matching the old
  // "ObjectID" spelling meant no _id or ref was ever recognised.
  await expect(page.locator(".erd")).toContainText("PK");
  await expect(page.locator(".erd")).toContainText("FK");
});

test("switches to the minimal diagram", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Minimal ERD" }).click();
  await expect(page.getByText(/Entities and their relationships only/)).toBeVisible();
  await expect(page.locator(".erd > svg")).toBeVisible();
});

test("shows the generated D2 source", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Show D2 source" }).click();
  const pre = page.locator("pre").first();
  await expect(pre).toContainText("shape: sql_table");
});

// Regression: the non-primitive branch omitted its newline, so Array and
// Embedded fields ran into the next field in the generated source.
test("every field is on its own line in the D2 source", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Show D2 source" }).click();
  const text = (await page.locator("pre").first().innerText()) ?? "";

  expect(text).toContain("roles: Array");
  expect(text).not.toMatch(/Array\w/);
  expect(text).not.toMatch(/Embedded\w/);
});

test("lists what was extracted from each model", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("User", { exact: true }).first()).toBeVisible();
  await expect(page.getByText(/instance method/).first()).toBeVisible();
});

test("code blocks are keyboard reachable", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("pre[tabindex='0']").first()).toBeAttached();
});

test("no horizontal overflow", async ({ page }) => {
  await page.goto("/");
  await expectNoHorizontalOverflow(page);
});

test("the demo page logs no errors", async ({ page }) => {
  const assertClean = failOnConsoleErrors(page);
  await page.goto("/");
  await page.getByRole("button", { name: "Minimal ERD" }).click();
  await page.waitForTimeout(400);
  assertClean();
});
